# Site settings
title: Soy Ángel.G
email: 
description: > # this means to ignore newlines until "baseurl:"
  Tan solo otro blog de un desarrollador en contínua formación.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://huorswords.github.io" # the base hostname & protocol for your site
twitter_username: angel_g_santos
github_username:  huorswords

# Build settings
markdown: kramdown
highlighter: rouge
encoding: utf-8
timezone: Europe/Madrid
remote_theme: mmistakes/minimal-mistakes